<Project>
  <PropertyGroup>
    <GameRoot Condition="'$(GameRoot)' == '' and '$(SILKSONG_GAME_ROOT)' != ''">$([System.IO.Path]::GetFullPath('$(SILKSONG_GAME_ROOT)'))\</GameRoot>
    <GameRoot Condition="'$(GameRoot)' == ''">$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\..\'))</GameRoot>
    <GameManagedDir>$(GameRoot)Hollow Knight Silksong_Data\Managed\</GameManagedDir>
    <BepInExCoreDir>$(GameRoot)BepInEx\core\</BepInExCoreDir>

    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
