<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>FreeHarpoonDash</AssemblyName>
    <RootNamespace>FreeHarpoonDash</RootNamespace>
    <Version>1.0.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(BepInExCoreDir)0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(BepInExCoreDir)BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GameManagedDir)Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="PlayMaker">
      <HintPath>$(GameManagedDir)PlayMaker.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GameManagedDir)UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(GameManagedDir)UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <Target Name="DeployMod" AfterTargets="Build" Condition="'$(DeployMod)' != 'false'">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(GameRoot)BepInEx\plugins\" />
  </Target>
</Project>
